import type { PaymentService, SummaryCard } from "./types"
import { AlertCircle, Clock, Activity, XCircle } from "lucide-react"

export const summaryCards: SummaryCard[] = [
  {
    title: "Recent Issues",
    value: "204",
    change: "+12.5%",
    trend: "up",
    icon: AlertCircle,
    iconColor: "text-orange-500",
  },
  {
    title: "Pending Issues",
    value: "34",
    change: "-10.4%",
    trend: "down",
    icon: Clock,
    iconColor: "text-amber-500",
  },
  {
    title: "Running Services",
    value: "34",
    change: "+12.5%",
    trend: "up",
    icon: Activity,
    iconColor: "text-green-500",
  },
  {
    title: "Interruptions",
    value: "204",
    change: "+12.5%",
    trend: "up",
    icon: XCircle,
    iconColor: "text-red-500",
  },
]

export const paymentServices: PaymentService[] = [
  {
    id: "1",
    service: "US Wire",
    priority: "High",
    region: "US",
    lastUpdated: new Date("2024-01-07"),
    today: "success",
    "6Jul": "error",
    "5Jul": "success",
    "4Jul": "text",
    "3Jul": "text",
    "2Jul": "text",
    "1Jul": "text",
    lastMonth: "text",
  },
  {
    id: "2",
    service: "APAC Payments",
    priority: "Medium",
    region: "APAC",
    lastUpdated: new Date("2024-01-06"),
    today: "success",
    "6Jul": "error",
    "5Jul": "success",
    "4Jul": "text",
    "3Jul": "text",
    "2Jul": "text",
    "1Jul": "text",
    lastMonth: "text",
  },
  {
    id: "3",
    service: "EMEA Payments",
    priority: "Low",
    region: "EMEA",
    lastUpdated: new Date("2024-01-05"),
    today: "success",
    "6Jul": "error",
    "5Jul": "success",
    "4Jul": "text",
    "3Jul": "text",
    "2Jul": "text",
    "1Jul": "text",
    lastMonth: "text",
  },
  {
    id: "4",
    service: "Singapore Payments",
    priority: "Critical",
    region: "APAC",
    lastUpdated: new Date("2024-01-08"),
    today: "success",
    "6Jul": "error",
    "5Jul": "error",
    "4Jul": "error",
    "3Jul": "error",
    "2Jul": "error",
    "1Jul": "error",
    lastMonth: "error",
  },
  {
    id: "5",
    service: "Global Wire Transfer",
    priority: "High",
    region: "Global",
    lastUpdated: new Date("2024-01-04"),
    today: "success",
    "6Jul": "success",
    "5Jul": "success",
    "4Jul": "success",
    "3Jul": "success",
    "2Jul": "success",
    "1Jul": "success",
    lastMonth: "success",
  },
  {
    id: "6",
    service: "Cross-Border Payments",
    priority: "Medium",
    region: "Global",
    lastUpdated: new Date("2024-01-03"),
    today: "error",
    "6Jul": "success",
    "5Jul": "text",
    "4Jul": "text",
    "3Jul": "text",
    "2Jul": "text",
    "1Jul": "text",
    lastMonth: "text",
  },
  {
    id: "7",
    service: "Domestic ACH",
    priority: "Low",
    region: "US",
    lastUpdated: new Date("2024-01-02"),
    today: "success",
    "6Jul": "success",
    "5Jul": "text",
    "4Jul": "text",
    "3Jul": "text",
    "2Jul": "text",
    "1Jul": "text",
    lastMonth: "text",
  },
  {
    id: "8",
    service: "Real-Time Payments",
    priority: "High",
    region: "US",
    lastUpdated: new Date("2024-01-01"),
    today: "success",
    "6Jul": "success",
    "5Jul": "text",
    "4Jul": "text",
    "3Jul": "text",
    "2Jul": "text",
    "1Jul": "text",
    lastMonth: "text",
  },
  {
    id: "9",
    service: "Mobile Payments",
    priority: "Medium",
    region: "Global",
    lastUpdated: new Date("2023-12-31"),
    today: "success",
    "6Jul": "success",
    "5Jul": "text",
    "4Jul": "text",
    "3Jul": "text",
    "2Jul": "text",
    "1Jul": "text",
    lastMonth: "text",
  },
]
